plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\zbail\\Downloads\\outclaw-light"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/sitemap.xml"

[headers.values]
Content-Type = "application/xml"